/**
 * The only icon import point (spec §5.6, §23.1). Features name icons by
 * meaning, so swapping the icon library later touches this file only.
 */
import { HugeiconsIcon } from "@hugeicons/react"
import {
  AiMagicIcon,
  Alert02Icon,
  AlertCircleIcon,
  Analytics01Icon,
  ArrowDown01Icon,
  ArrowDownRight01Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  ArrowUp01Icon,
  ArrowUpDownIcon,
  ArrowUpRight01Icon,
  BarCode01Icon,
  Briefcase01Icon,
  Building03Icon,
  Calendar03Icon,
  Cancel01Icon,
  CashierIcon,
  CheckListIcon,
  CheckmarkCircle02Icon,
  Clock01Icon,
  Coins01Icon,
  CommandIcon,
  ComputerIcon,
  Copy01Icon,
  CreditCardIcon,
  CustomerSupportIcon,
  DashboardSquare01Icon,
  Delete02Icon,
  DeliveryReturn01Icon,
  DeliveryTruck01Icon,
  DiscountTag01Icon,
  Download04Icon,
  Edit02Icon,
  Factory01Icon,
  File01Icon,
  FilterHorizontalIcon,
  Folder01Icon,
  GiftIcon,
  GlobeIcon,
  HelpCircleIcon,
  Home01Icon,
  Image01Icon,
  InformationCircleIcon,
  Invoice01Icon,
  Key01Icon,
  LayoutGridIcon,
  LinkSquare02Icon,
  Loading03Icon,
  Logout01Icon,
  Mail01Icon,
  Megaphone01Icon,
  Menu01Icon,
  MinusSignIcon,
  Money03Icon,
  Moon02Icon,
  MoreHorizontalIcon,
  MoreVerticalIcon,
  Notification01Icon,
  PackageIcon,
  PaintBoardIcon,
  PercentCircleIcon,
  Plug01Icon,
  PlusSignIcon,
  PuzzleIcon,
  RefreshIcon,
  Restaurant01Icon,
  Search01Icon,
  Settings01Icon,
  Shield01Icon,
  ShoppingBag01Icon,
  ShoppingCart01Icon,
  SidebarLeftIcon,
  SmartPhone01Icon,
  StarIcon,
  Store01Icon,
  Sun03Icon,
  Tag01Icon,
  Task01Icon,
  TaxesIcon,
  Tick02Icon,
  Upload04Icon,
  UserAdd01Icon,
  UserCircleIcon,
  UserGroupIcon,
  UserIcon,
  ViewIcon,
  ViewOffIcon,
  Wallet01Icon,
  WarehouseIcon,
  Wrench01Icon,
} from "@hugeicons/core-free-icons"
import type { ComponentProps } from "react"

export const icons = {
  add: PlusSignIcon,
  ai: AiMagicIcon,
  alert: Alert02Icon,
  analytics: Analytics01Icon,
  arrowDown: ArrowDown01Icon,
  arrowLeft: ArrowLeft01Icon,
  arrowRight: ArrowRight01Icon,
  arrowUp: ArrowUp01Icon,
  barcode: BarCode01Icon,
  billing: CreditCardIcon,
  booking: Calendar03Icon,
  building: Building03Icon,
  calendar: Calendar03Icon,
  cashier: CashierIcon,
  catalog: ShoppingBag01Icon,
  check: Tick02Icon,
  checklist: CheckListIcon,
  close: Cancel01Icon,
  clock: Clock01Icon,
  cms: LayoutGridIcon,
  coins: Coins01Icon,
  command: CommandIcon,
  copy: Copy01Icon,
  customers: UserGroupIcon,
  dashboard: DashboardSquare01Icon,
  delete: Delete02Icon,
  device: ComputerIcon,
  discount: DiscountTag01Icon,
  download: Download04Icon,
  edit: Edit02Icon,
  error: AlertCircleIcon,
  external: LinkSquare02Icon,
  file: File01Icon,
  filter: FilterHorizontalIcon,
  folder: Folder01Icon,
  gift: GiftIcon,
  globe: GlobeIcon,
  help: HelpCircleIcon,
  hide: ViewOffIcon,
  home: Home01Icon,
  hr: Briefcase01Icon,
  image: Image01Icon,
  info: InformationCircleIcon,
  integrations: Plug01Icon,
  inventory: WarehouseIcon,
  invoice: Invoice01Icon,
  key: Key01Icon,
  loading: Loading03Icon,
  logout: Logout01Icon,
  mail: Mail01Icon,
  manufacturing: Factory01Icon,
  marketing: Megaphone01Icon,
  menu: Menu01Icon,
  minus: MinusSignIcon,
  money: Money03Icon,
  moon: Moon02Icon,
  more: MoreHorizontalIcon,
  moreVertical: MoreVerticalIcon,
  notifications: Notification01Icon,
  orders: ShoppingCart01Icon,
  percent: PercentCircleIcon,
  phone: SmartPhone01Icon,
  products: PackageIcon,
  projects: Task01Icon,
  refresh: RefreshIcon,
  repair: Wrench01Icon,
  restaurant: Restaurant01Icon,
  returns: DeliveryReturn01Icon,
  search: Search01Icon,
  security: Shield01Icon,
  settings: Settings01Icon,
  shipping: DeliveryTruck01Icon,
  show: ViewIcon,
  sidebar: SidebarLeftIcon,
  sort: ArrowUpDownIcon,
  star: StarIcon,
  store: Store01Icon,
  success: CheckmarkCircle02Icon,
  sun: Sun03Icon,
  support: CustomerSupportIcon,
  tag: Tag01Icon,
  tax: TaxesIcon,
  theme: PaintBoardIcon,
  trendDown: ArrowDownRight01Icon,
  trendUp: ArrowUpRight01Icon,
  upload: Upload04Icon,
  user: UserIcon,
  userAdd: UserAdd01Icon,
  userCircle: UserCircleIcon,
  wallet: Wallet01Icon,
  modules: PuzzleIcon,
} as const

export type IconName = keyof typeof icons
export type IconSvg = (typeof icons)[IconName]

type IconProps = Omit<ComponentProps<typeof HugeiconsIcon>, "icon"> & {
  name: IconName
}

/**
 * `<Icon name="orders" />`. Inside buttons add `data-icon="inline-start"`;
 * components size icons themselves, so no size classes are needed there.
 */
export function Icon({ name, strokeWidth = 2, ...props }: IconProps) {
  return (
    <HugeiconsIcon
      icon={icons[name]}
      strokeWidth={strokeWidth}
      aria-hidden={props["aria-label"] ? undefined : true}
      {...props}
    />
  )
}
