// Generates packages/contract/src/generated/** from the pinned backend
// bundle (spec §13.3). Output is committed; CI regenerates and fails on a diff.
import { createHash } from "node:crypto"
import { mkdir, readFile, writeFile } from "node:fs/promises"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

import openapiTS, { astToString } from "openapi-typescript"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const bundle = join(root, "bundle")
const out = join(root, "src", "generated")

const HEADER = "// Generated by `pnpm contract:generate` from packages/contract/bundle. Do not edit.\n"

const readJson = async (file) => JSON.parse(await readFile(join(bundle, file), "utf8"))

const literalUnion = (values) =>
  values.length === 0 ? "never" : values.map((v) => JSON.stringify(v)).join("\n  | ")

async function writeOut(file, body) {
  await writeFile(join(out, file), HEADER + body)
}

async function generatePaths(context) {
  const source = new URL(`file:///${join(bundle, `${context}.openapi.json`).replace(/\\/g, "/")}`)
  const ast = await openapiTS(source, { alphabetize: true })
  await writeOut(`${context}.ts`, `/* eslint-disable */\n${astToString(ast)}`)
}

async function generateRegistries() {
  const modules = await readJson("modules.json")
  const limits = await readJson("limits.json")
  const errorCodes = await readJson("error-codes.json")
  const storefront = await readJson("storefront.json")
  const tenantPermissions = (await readJson("permissions.tenant.json")).permissions
  const landlordPermissions = (await readJson("permissions.landlord.json")).permissions

  const body = `
export type ModuleKey =
  | ${literalUnion(modules.map((m) => m.key))}

export type ModuleDefinition = {
  readonly key: ModuleKey
  readonly name: string
  readonly class: "module" | "submodule" | "capability" | "vertical" | "integration"
  readonly requires: readonly ModuleKey[]
  readonly activation: "auto" | "manual"
  readonly readWhenInactive: boolean
  readonly windDown: readonly string[]
}

export const modules: readonly ModuleDefinition[] = ${JSON.stringify(
    modules.map((m) => ({
      key: m.key,
      name: m.name,
      class: m.class,
      requires: m.requires,
      activation: m.activation,
      readWhenInactive: m.read_when_inactive,
      windDown: m.wind_down,
    })),
    null,
    2,
  )}

export type LimitKey =
  | ${literalUnion(limits.map((l) => l.key))}

export type LimitDefinition = {
  readonly key: LimitKey
  readonly label: string
  readonly kind: "count" | "storage" | "rate"
  readonly unlimitedAllowed: boolean
}

export const limits: readonly LimitDefinition[] = ${JSON.stringify(
    limits.map((l) => ({ key: l.key, label: l.label, kind: l.kind, unlimitedAllowed: l.unlimited_allowed })),
    null,
    2,
  )}

/** Backend error codes (literal codes at throw sites); some codes are built at runtime and are not listed. */
export type BackendErrorCode =
  | ${literalUnion(errorCodes.map((e) => e.code))}

export type TenantPermission =
  | ${literalUnion(tenantPermissions)}

export type LandlordPermission =
  | ${literalUnion(landlordPermissions)}

export const storefrontThemes = ${JSON.stringify(storefront.themes)} as const
export type StorefrontTheme = (typeof storefrontThemes)[number]

export const storefrontFonts = ${JSON.stringify(storefront.fonts)} as const
export type StorefrontFont = (typeof storefrontFonts)[number]
`
  await writeOut("registries.ts", body)
}

async function generateRoutes(context) {
  const routes = await readJson(`routes.${context}.json`)
  const entries = {}

  for (const r of routes) {
    entries[r.name] = {
      methods: r.methods,
      uri: r.uri,
      group: r.group,
      actor: r.actor,
      module: r.module,
      permission: r.permission,
      windDown: r.wind_down,
      readWhenInactive: r.read_when_inactive,
      idempotency: r.idempotency,
      usageLimit: r.usage_limit,
    }
  }

  const typeName = context === "tenant" ? "TenantRouteName" : "LandlordRouteName"
  const body = `
import type { RouteEntry } from "../manifest"

export type ${typeName} = keyof typeof ${context}Routes

export const ${context}Routes = ${JSON.stringify(entries)} as const satisfies Record<string, RouteEntry>
`
  await writeOut(`routes.${context}.ts`, body)
}

async function writeLock() {
  const files = [
    "landlord.openapi.json",
    "tenant.openapi.json",
    "routes.landlord.json",
    "routes.tenant.json",
    "modules.json",
    "limits.json",
    "permissions.landlord.json",
    "permissions.tenant.json",
    "error-codes.json",
    "storefront.json",
  ]
  const lock = { files: {} }

  for (const file of files) {
    lock.files[file] = createHash("sha256").update(await readFile(join(bundle, file))).digest("hex")
  }

  let previous = {}
  try {
    previous = JSON.parse(await readFile(join(root, "contract.lock.json"), "utf8"))
  } catch {
    // First generation.
  }

  await writeFile(join(root, "contract.lock.json"), JSON.stringify({ backendCommit: previous.backendCommit ?? null, ...lock }, null, 2) + "\n")
}

await mkdir(out, { recursive: true })
await Promise.all([generatePaths("landlord"), generatePaths("tenant"), generateRegistries(), generateRoutes("tenant"), generateRoutes("landlord")])
await writeLock()
console.log("Contract generated.")
